import React from 'react'
import { Card } from '@/components/common/Card'
import { GitPullRequest, FolderGit2, CheckCircle2 } from 'lucide-react'
import { Button } from '@/components/common/Button'

interface PRPreviewProps {
  title: string
  description: string
  branch: string
  filesChanged: number
  onCreatePR?: () => void
}

export const PRPreview: React.FC<PRPreviewProps> = ({ title, description, branch, filesChanged, onCreatePR }) => (
  <Card className="border-slate-border/40 bg-slate-surface/30 backdrop-blur-md p-5 select-none">
    <div className="space-y-5">
      <div className="flex items-center gap-2 pb-3.5 border-b border-slate-border/20">
        <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-450 text-emerald-450 text-emerald-400">
          <GitPullRequest size={16} />
        </div>
        <div>
          <h3 className="text-sm font-bold text-slate-100 font-display">Pull Request Proposal</h3>
          <p className="text-[10px] text-slate-500 font-mono">AUTOGENERATED REFACTOR PIPELINE</p>
        </div>
      </div>
      
      <div>
        <h4 className="text-xs font-bold text-slate-200 font-display">{title}</h4>
        <p className="text-xs text-slate-400 mt-1 leading-relaxed font-sans">{description}</p>
      </div>

      <div className="grid grid-cols-2 gap-4 text-xs bg-slate-950/20 p-3.5 rounded-xl border border-slate-border/20 font-mono">
        <div>
          <p className="text-slate-500 mb-1">Target Branch</p>
          <p className="text-indigo-400 truncate flex items-center gap-1.5" title={branch}>
            <FolderGit2 size={12} />
            {branch}
          </p>
        </div>
        <div>
          <p className="text-slate-500 mb-1">Files Impacted</p>
          <p className="text-slate-200 font-bold">{filesChanged} code file</p>
        </div>
      </div>

      {onCreatePR && (
        <Button
          onClick={onCreatePR}
          variant="primary"
          size="md"
          className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 shadow-emerald-500/10 hover:shadow-emerald-500/25 border-transparent text-white"
        >
          <CheckCircle2 size={16} />
          <span>Stage Pull Request</span>
        </Button>
      )}
    </div>
  </Card>
)

